### ISSUE TITLE
make a library

### ISSUE THREAD

**Issue by Ennoriel** [rajasegar/svelte-slides#6]
Hello!

I think your template is awesome! Would you like to make a library out of the few utils components? and maybe the reveal initialization?

If not, I'll probably do it since it'll be easier to use it for myself and in the long run to maintain and update it. We can aslo do it with 4 hands if you prefer!

Thanks!

**Comment by rajasegar** [comment]
@Ennoriel I am not sure I clearly understood your proposal, but anyway I would like to see the implementation. You can work on it and please let me know, since I don't have any bandwidth to contribute.

**Comment by Ennoriel** [comment]
I published a library based on your work: https://www.npmjs.com/package/svelte-reveal.js
I made it with Svelte Kit in mind but it's probably working with a Svelte/Vite project!
